### ISSUE TITLE
[PE-D][Tester D] Inaccurate Error Message for Editing RECIPE_DURATION

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T13-2/tp#212]
When I input an invalid value for RECIPE_DURATION for `edit`, the error message displayed is telling me that I have to input at least 1 field to edit, which I already did. Would a better message be to tell me that the input is incorrect?

![image.png](https://raw.githubusercontent.com/eugenetangkj/ped/main/files/5156ecea-6042-46c8-a83c-f2caadeacf36.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: eugenetangkj/ped#4

**Comment by filbertphang** [comment]
Fixed in #245 

negative numbers are also not allowed for portion/duration ranges (will not match the regex), so the proper error message is thrown in that case too
