### ISSUE TITLE
[PE-D][Tester D] Addf command does not allow me to submit a recipe

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T13-2/tp#224]
I tried the following input fields for the `addf` command. After I am done, I press `Save`.

![image.png](https://raw.githubusercontent.com/eugenetangkj/ped/main/files/b2bc38c5-a9ca-49d1-9481-f5dc8d8eda43.png)

However, I got the following error:

![image.png](https://raw.githubusercontent.com/eugenetangkj/ped/main/files/40b23e3b-d019-4dd6-ba39-115cd66ebbfe.png)

I am unsure of why the recipe cannot be added since I entered most of the values as suggested in the placeholder text of the input boxes.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: eugenetangkj/ped#6

**Comment by filbertphang** [comment]
error messages fixed in #245
