### ISSUE TITLE
[PE-D][Tester B] Edit item window shows wrong ingredient input format

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T13-2/tp#225]
![image.png](https://raw.githubusercontent.com/Jxleejiaxin/ped/main/files/b6ac4ba0-a974-4ff9-84f2-cbeb2406079b.png)

Rather than -FLAG it is showing FLAG/.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: Jxleejiaxin/ped#6

**Comment by filbertphang** [comment]
duplicate issue as #223
