### ISSUE TITLE
[PE-D][Tester D] Inconsistent naming of application for error message when no substitutions are available

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T13-2/tp#228]
Was this intended to be called `RecipeBook`, or is a renaming to `Rizzipe` required?

![image.png](https://raw.githubusercontent.com/eugenetangkj/ped/main/files/fb5f90f4-b950-43d7-96e3-7ad8e0564c95.png)

On a side note, this is also present for the `clear` command.

![image.png](https://raw.githubusercontent.com/eugenetangkj/ped/main/files/d0504391-6004-4d2d-9abe-ce7651307081.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: eugenetangkj/ped#7

**Comment by JamesLiuZX** [comment]
No actions required. Rizzipe is simply the name of the application, like how Gmail inbox is called 'Inbox' despite the app being called 'Gmail'. For all purposes of the app, recipe book is the instance of the data structure which can be included in logging messages and display messages.
