### ISSUE TITLE
[PE-D][Tester A] Input format does not match the error shown

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T13-2/tp#230]
![4.JPG](https://raw.githubusercontent.com/Bentimate/ped/main/files/95232626-857a-47fd-8ddf-755340b9c0ae.JPG)

Although the error states that alphanum characters, numbers were not accepted as seen in picture.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Bentimate/ped#4

**Comment by filbertphang** [comment]
Fixed in #245 

regex for `Name` has been relaxed (and is now consistent with the error message)
