### ISSUE TITLE
[PE-D][Tester A] Suggested input not accepted

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T13-2/tp#232]
![4.JPG](https://raw.githubusercontent.com/Bentimate/ped/main/files/0252154b-5c75-4786-9465-5b995ca128de.JPG)

![4.1.JPG](https://raw.githubusercontent.com/Bentimate/ped/main/files/38bc8e49-356f-434b-af93-849b3feef5d5.JPG)

Suggested input in the popup window ran into an error

attempted input:

![4.2.JPG](https://raw.githubusercontent.com/Bentimate/ped/main/files/57739144-030d-4773-8c25-5f1140e92d00.JPG)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Bentimate/ped#5

**Comment by filbertphang** [comment]
tldr: 
- edit form ingredient suggestion uses the wrong syntax: `a/` instead of `-a`
- add form is missing ingredient suggestions
