### ISSUE TITLE
[PE-D][Tester D] Buggy shortcut for deleting recipes

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T13-2/tp#236]
I am able to trigger the shortcut for deleting recipes even though the screen does not show me having any recipes selected (based on my understanding, a selected receipt will be highlighted blue right?).

<i><video controls><source src="https://raw.githubusercontent.com/eugenetangkj/ped/main/files/0c450e05-fe86-4840-95ad-7fa47e3d36f9.mp4" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/eugenetangkj/ped/main/files/0c450e05-fe86-4840-95ad-7fa47e3d36f9.mp4</i>

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: eugenetangkj/ped#8

**Comment by SeeuSim** [comment]
Delete key bind needs to work only when focus is on recipe list card
