### ISSUE TITLE
[PE-D][Tester D] Unable to insert multiple tags via edit pop up form

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T13-2/tp#237]
Suppose I have selected a receipe and press `f` to open up the edit pop up form. While I am able to add `Ingredients` and `Steps` by clicking on their respective last boxes, for `Tags`, I am unable to add multiple tags. When I insert `Italian Food` into the box for `Tags`, it will be saved as one single tag. May I check why the feature to add multiple tags is not included since it exists for `Ingredients` and `Steps`? This makes it hard for users to use this feature to edit tags since users can only edit 1 tag at a time.

Before:

![image.png](https://raw.githubusercontent.com/eugenetangkj/ped/main/files/9069ddae-ea99-45c4-8269-e60af18631d8.png)

After clicking save:

![image.png](https://raw.githubusercontent.com/eugenetangkj/ped/main/files/2aa97b35-4163-41f9-927e-e316d3fe7b66.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: eugenetangkj/ped#9

**Comment by filbertphang** [comment]
documentation issue, it should be noted that tags in forms are comma-separated
