### ISSUE TITLE
[PE-D][Tester D] Overzealous Input Validation for RECIPE_DURATION

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T13-2/tp#240]
The following inputs do not work:

![image.png](https://raw.githubusercontent.com/eugenetangkj/ped/main/files/0b656bd0-a2da-4726-b83a-ad1f771bbaaf.png)

![image.png](https://raw.githubusercontent.com/eugenetangkj/ped/main/files/dfc553b2-147d-4141-ab82-04f8461755d6.png)

The following inputs work:

![image.png](https://raw.githubusercontent.com/eugenetangkj/ped/main/files/19cd958a-2a68-4ecd-9460-08e48d884eb7.png)

![image.png](https://raw.githubusercontent.com/eugenetangkj/ped/main/files/ac004676-5dcd-4c38-b5f7-a6721535b789.png)

I understand where you are coming from, and it's a good effort in considering the two different cases (whether singular or plural). However, from a user's perspective, not putting an additional `s` for plural terms should not deny him/her from being able to input a given value because what are important are the numerical value and the unit of measurement, instead of grammatical issues.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: eugenetangkj/ped#11

**Comment by filbertphang** [comment]
Fixed in #245 

relaxed regex for `RecipeDuration` and `RecipePortion`
